name = "Beg"
license = "MIT"
licenselink = "https://github.com/dim0627/hugo_theme_beg/blob/master/LICENSE.md"
description = "Bootstrap3 based theme for Hugo."
homepage = "https://github.com/dim0627/hugo_theme_beg"
tags = ["blog"]
features = ["responsive", "thumbnail", "syntax highlight", "structured data", "ogp", "twitter cards"]
min_version = 0.42.2

[author]
  name = "Daisuke Tsuji"
  homepage = "https://yet.unresolved.xyz/"

